# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'University of Toledo' 
    description: 'Personal website of Bernardo Rivas.' # Personalized description
    twitter: '' 
  analytics:
    google_analytics: '' 
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: '' 
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Bernardo Rivas"

# Site footer
footer:
  copyright:
    notice: '© {year} Bernardo Rivas. This work is licensed under {license}'
    license:
      enable: true
      # These are common Creative Commons settings (CC BY-NC-SA)
      # Adjust as per your preference. See https://creativecommons.org/choose/
      allow_derivatives: false # NoDerivatives = false, ShareAlike implies derivatives are allowed but must be shared under same terms
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006' # Default US date format
  time_format: '3:04 PM'    # Default US time format

# Site features
features:
  math:
    enable: true 
  privacy_pack:
    enable: false 